### PR TITLE
h2,h3 styling removed

### PR DESCRIPTION
**Pull request by prasunanand**
headings collapsed with the contents on mobile devices.

### CODE REVIEW

**Comment by greenify** [comment]
I am not so sure whether removing the `h2` styles without other changes is a good idea, because it leads to a lot of whitespace for the tutorial headings ...

**Comment by daviddao** [comment]
@greenify - I agree, we should fix this in a responsive way

**Comment by greenify** [comment]
@prasunanand: how did you merge that? 

```
<<<<<<< HEAD
```

shouldn't be part of a file! Do you mind to wrap your changes in a clean PR?

**Comment by prasunanand** [comment]
@greenify That was a mistake . I was updating my local repo.

**Pull request closed without merging**
