### PR TITLE
redirect directly from start page and add slack chat link to 101 intro

### PR DESCRIPTION
**Pull request by jessica-jordan**
minor fix of 
- redirecting directly from the start page once action button is clicked and
- updating community resources section

### CODE REVIEW

**Comment by greenify** [comment]
I thought `biojavscript` is the non-public mailing list - did this change?

**Comment by jessica-jordan** [comment]
@greenify You are right, it is still a non-public mailing list, but I am afraid that due to the amount of spam we had on the public one, almost no one is using the /biojs forum anymore. Therefore I think it's better to  direct people to the private one and let them ask for access (if they don't have any access yet), rather than linking to the barely used forum that is long outdated

**Comment by greenify** [comment]
Sure - hmm that' sad to hear. You should have changed the permission of senders to members only earlier, maybe my fault. LGTM then

**Comment by daviddao** [comment]
Thanks for the effort @jessica-jordan !

**Pull request merged**
